menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/ghostpancn

favicon: /tiger_head_round.png
logo: /flat_red_ghostpan.png

# Comment
# e.g disqus: seansun
disqus: seansun
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
